# Generated by Django 4.0.2 on 2023-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_id', models.IntegerField(verbose_name='Id кнопки')),
                ('page_id', models.IntegerField(verbose_name='Id страницы')),
                ('text', models.CharField(max_length=60)),
                ('print_file', models.CharField(max_length=60)),
                ('redirection_page', models.IntegerField(verbose_name='Id страницы перенаправления')),
            ],
            options={
                'unique_together': {('button_id', 'page_id')},
            },
        ),
    ]
