# Generated by Django 4.0.2 on 2023-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_buttons',
            name='print_file',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='menu_buttons',
            name='redirection_page',
            field=models.IntegerField(default=-1, verbose_name='Id страницы перенаправления'),
        ),
        migrations.AlterField(
            model_name='menu_buttons',
            name='text',
            field=models.CharField(default='', max_length=60),
        ),
    ]
