# Generated by Django 4.0.2 on 2023-06-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_menu_buttons_print_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_id', models.IntegerField(verbose_name='Id кнопки')),
                ('text', models.CharField(default='', max_length=60)),
                ('print_file', models.CharField(default='-', max_length=60)),
                ('redirection_page', models.IntegerField(default=-1, verbose_name='Id страницы перенаправления')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(verbose_name='Id страницы')),
                ('name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu_Buttons',
        ),
        migrations.AddField(
            model_name='menubuttons',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pages'),
        ),
        migrations.AlterUniqueTogether(
            name='menubuttons',
            unique_together={('button_id', 'page')},
        ),
    ]
