# Generated by Django 4.0.2 on 2023-06-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menubuttons_pages_delete_menu_buttons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menubuttons',
            name='redirection_page',
        ),
        migrations.AddField(
            model_name='menubuttons',
            name='redirect_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_page', to='core.pages', verbose_name='Страница переадресации'),
        ),
        migrations.AlterField(
            model_name='menubuttons',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='core.pages', verbose_name='Страница с кнопкой'),
        ),
        migrations.AlterField(
            model_name='menubuttons',
            name='print_file',
            field=models.CharField(default='-', max_length=60, verbose_name='Файл для печати'),
        ),
        migrations.AlterField(
            model_name='menubuttons',
            name='text',
            field=models.CharField(default='', max_length=60, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Название страницы'),
        ),
    ]
