# Generated by Django 4.0.2 on 2023-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_operators_tickets_alter_menubuttons_redirect_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='taken',
            field=models.BooleanField(default=False, verbose_name='Принят в работу'),
        ),
    ]
