# Generated by Django 4.2.1 on 2023-06-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_queue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queue',
            new_name='Queues',
        ),
    ]
