# Generated by Django 4.2.1 on 2023-06-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_queue_queues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queues',
        ),
    ]
