# Generated by Django 4.2.1 on 2023-06-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_queues'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(verbose_name='Номер талона')),
                ('question', models.CharField(max_length=60, verbose_name='Вопрос')),
                ('taken', models.BooleanField(default=False, verbose_name='Принят в работу')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_number', models.IntegerField(verbose_name='Номер окна')),
                ('current_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.experttickets', verbose_name='Текущий посетитель')),
            ],
        ),
    ]
