# Generated by Django 4.2.1 on 2023-06-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_experttickets_expert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expert',
            new_name='Experts',
        ),
        migrations.DeleteModel(
            name='ExpertTickets',
        ),
        migrations.AlterField(
            model_name='experts',
            name='current_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tickets', verbose_name='Текущий посетитель'),
        ),
    ]
